mail/p5-Mail-Milter-Authentication: various fixes
Functions:

- Use log_dispatchouli instead of error_log.  /var/log/maillog is the
  default log file.
- Fix $MYARGS for Log::Dispatchouli to make the default args work.

Style:

- Use shebangfix to fix "#!env perl" in PREFIX/bin/authentication_milter*.
- Use EXTRACT_AFTER_ARGS instead of using rm(1) in the post-extract target.
- Simplify SUB_LIST using "for".
- Simplify post-patch using ${REINPLACE_ARGS}.
- Create runtime directories such as CACHEDIR in the rc.d script, not the package.
- No longer LOGDIR, use syslog instead.

Fixes in the rc.d script:

- Do not use ${name}_user and ${name}_group because the authentication_milter
  switches the user and the group by itself.
- Simplify precmd for "start".  It now creates the runtime directories.
- Remove the [ -d conditional.  install(8) works even if the directory exists.
- Define $procname properly.
- Remove a_m_stop and a_m_start.  The rc.d framework works fine.

SPECIAL THANKS:
  Reviewed by Hiroki Sato <hrs@FreeBSD.org>

diff --git a/mail/p5-Mail-Milter-Authentication/files/authentication_milter.in b/mail/p5-Mail-Milter-Authentication/files/authentication_milter.in
--- a/mail/p5-Mail-Milter-Authentication/files/authentication_milter.in
+++ b/mail/p5-Mail-Milter-Authentication/files/authentication_milter.in
@@ -18,72 +18,76 @@
 # authentication_milter_flags="<set as needed>"
 # authentication_milter_prefix="%%ETCDIR%%"
 # authentication_milter_foreground_enable="<default 'NO'>"
-# authentication_milter_user="%%DEFAULT_USER%%"
-# authentication_milter_group="%%DEFAULT_GROUP%%"
 #
 
 . /etc/rc.subr
 
 name="authentication_milter"
 rcvar="authentication_milter_enable"
+procname="${name}:parent"
 
 load_rc_config $name
 
 : ${authentication_milter_enable:=NO}
 : ${authentication_milter_prefix:=%%ETCDIR%%}
 : ${authentication_milter_foreground_enable:=NO}
-: ${authentication_milter_user:=%%DEFAULT_USER%%}
-: ${authentication_milter_group:=%%DEFAULT_GROUP%%}
 
 pidfile="%%RUNDIR%%/${name}.pid"
-procname="%%PREFIX%%/bin/authentication_milter"
-command_args="--pidfile ${pidfile} --prefix ${authentication_milter_prefix} ${authentication_milter_flags}"
+command="%%PREFIX%%/bin/authentication_milter"
+command_args="--pidfile ${pidfile} --prefix ${authentication_milter_prefix} ${command_args}"
 
-start_cmd="authentication_milter_start"
-start_precmd="authentication_milter_prestart"
-status_cmd="authentication_milter_status"
-stop_cmd="authentication_milter_stop"
+start_precmd="authentication_milter_precmd_start"
+stop_precmd="authentication_milter_precmd"
 
-authentication_milter_prestart () {
+authentication_milter_precmd_start () {
+	var1=
+	var2=
+
 	case "${authentication_milter_flags}" in
 	-c*|*-c*|--control*|*--control*)
-		err 1 "authentication_milter_flags doesn't require --control option."
+		var1="control"
 		;;
 	-d*|*-d*|--daemon*|*--daemon*)
-		err 1 "authentication_milter_flags doesn't require --daemon option."
+		var1="daemon"
 		;;
 	--pidfile*|*--pidfile*)
-		err 1 "authentication_milter_flags doesn't require --pidfile option."
+		var2="pidfile"
 		;;
 	--prefix*|*--prefix*)
-		err 1 "authentication_milter_flags doesn't require --prefix option."
+		var2="prefix"
 		;;
 	-h*|*-h*|--help*|*--help*)
-		err 1 "authentication_milter_flags doesn't require --help option."
+		var1="help"
 		;;
+	esac
+	case ${var1} in
+	"")	;;
+	*)
+		err 1 "Invalid option --${var1} found in ${name}_flags"
+	;;
+	esac
+	case ${var2} in
+	"")	;;
+	*)
+		err 1 "Invalid option --${var2} found in ${name}_flags." \
+		    "Use \$${name}_${var2} in /etc/rc.conf instead."
+	;;
 	esac
 
 	piddir=$(dirname "$pidfile")
-	if [ ! -d "$piddir" ]; then
-		install -d -o "$authentication_milter_user" -g "$authentication_milter_group" -m 0755 "$piddir"
+	install -d %%VARLIBDIRBASE%%
+	install -d -m 0755 -o "%%DEFAULT_USER%%" -g "%%DEFAULT_GROUP%%" "$piddir"
+	install -d -m 0750 -o "%%DEFAULT_USER%%" -g "%%DEFAULT_GROUP%%" \
+	    %%RUNDIR%% %%CACHEDIR%% %%SPOOLDIR%% %%VARLIBDIR%%
+
+	authentication_milter_precmd
+	if ! checkyesno authentication_milter_foreground_enable; then
+		command_args="-d ${command_args}"
 	fi
 }
 
-authentication_milter_start () {
-	if checkyesno authentication_milter_foreground_enable; then
-		${procname}    -c start  ${command_args}
-	else
-		echo "Starting ${name}."
-		${procname} -d -c start  ${command_args}
-	fi
-}
-
-authentication_milter_stop () {
-		${procname}    -c stop   ${command_args}
-}
-
-authentication_milter_status () {
-		${procname}    -c status ${command_args}
+authentication_milter_precmd () {
+	command_args="-c ${rc_arg} ${command_args}"
 }
 
 run_rc_command "$1"
